### ISSUE TITLE
Should I set expectedCyclesThatMakeChanges to 2 in RecipeSpec?

### ISSUE THREAD

**Issue by heyuanliu-intel** [heyuanliu-intel/qat-openrewrite#3]
The testcase always fails according to the "Expected recipe to complete in 1 cycle, but took at least one more cycle. "
So should I set expectedCyclesThatMakeChanges to 2?

If I make below change, the testcase will success.

 spec.recipe(recipe).parser(JavaParser.fromJavaVersion()
                .logCompilationWarningsAndErrors(true)
                .classpath("guava"))**.expectedCyclesThatMakeChanges(2)**;

If I don't set the expectedCyclesThatMakeChanges to 2, it will fails and below is the output.

`
SSLContextQATRecipeTest > replaceSSLContextWithProvider() FAILED
    java.lang.AssertionError: Expected recipe to complete in 1 cycle, but took 2 cycles.
        at org.openrewrite.test.RecipeSchedulerCheckingExpectedCycles.verify(RecipeSchedulerCheckingExpectedCycles.java:70)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:371)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:74)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:69)
        at org.openrewrite.qat.SSLContextQATRecipeTest.replaceSSLContextWithProvider(SSLContextQATRecipeTest.java:82)

Gradle Test Executor 6 finished executing tests.

> Task :test FAILED

SSLContextQATRecipeTest > replaceSSLContext() FAILED
    java.lang.AssertionError: Expected recipe to complete in 1 cycle, but took 2 cycles.
        at org.openrewrite.test.RecipeSchedulerCheckingExpectedCycles.verify(RecipeSchedulerCheckingExpectedCycles.java:70)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:371)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:74)
        at org.openrewrite.test.RewriteTest.rewriteRun(RewriteTest.java:69)
        at org.openrewrite.qat.SSLContextQATRecipeTest.replaceSSLContext(SSLContextQATRecipeTest.java:54)

3 tests completed, 3 failed
Finished generating test XML results (0.001 secs) into: /home/dev/Projects/qat-openrewrite/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.002 secs) into: /home/dev/Projects/qat-openrewrite/build/reports/tests/test
Watching 27 directories to track changes
Watching 32 directories to track changes
Watching 33 directories to track changes
:test (Thread[Execution worker Thread 5,5,main]) completed. Took 19.587 secs.

`

**Comment by heyuanliu-intel** [comment]
**Below is the comments from Sam Snyder:**

That's also why the recipe was running for more cycles than expected.
Without declining to change code that already fits the recipes desired output, no number of cycles will be enough as the recipe will always continue to make more changes
